tickers: ['AAPL', 'AMZN', 'GOOG', 'META', "NFLX"]
stock_data_path: "./data/"
max_iterations: 10000
convergence_threshold: 1e-6
convergence_window: 100
risk_free_rate: 0.08877 # (in decimal, not percentage), got this value by averaging the risk-free rates of the time period 2014.01.01 to 2019.12.31, refer to c
min_weight: 0.01
metric: 'sharpe_ratio' # 'sharpe_ratio', 'return', 'volatility'

Simulated_Annealing:
  initial_temperature: 100
  alpha: 0.95
  beta: 0.95
  stopping_temperature: 1e-6
  schedule: 'lundy_mees' # 'linear', 'geometric', 'lundy_mees'

Particle_Swarm_Optimization:
  num_particles: 10
  inertia: 0.65
  cognitive: 2.5
  social: 2.5

Genetic_Algorithm:
  population_size: 10
  selection_method: 'tournament' # 'tournament', 'roulette_wheel', 'rank_based'
  tournament_size: 3
  crossover_method: 'uniform' # 'uniform', 'one_point', 'two_point'
  crossover_rate: 0.8
  mutation_rate: 0.01 # should be small, better 1/self.stock_num
  replacement_method: 'elitism' # 'elitism', 'generational'

Ant_Colony_Optimization:
  num_ants: 10

Markowitz_Model:
