tickers: ["JPM", "BAC", "JNJ", "PFE", "PG", "KO", "XOM", "CVX", "BA", "CAT"]
stock_data_path: "./data/"
max_iterations: 1000
convergence_threshold: 1e-6
convergence_window: 100
risk_free_rate: 0.8877 # (in percentage, not decimal), got this value by averaging the risk-free rates of the time period 2014.01.01 to 2019.12.31, refer to https://fred.stlouisfed.org/series/DTB3
min_weight: 0.01
metric: 'sharpe_ratio' # 'sharpe_ratio', 'return', 'volatility'

# Flags to control which algorithms to run
# Set to True to run the corresponding algorithm, False to skip it
run_ga: True
run_sa: False
run_pso: False
runs: 10 # Number of runs for each algorithm

Simulated_Annealing:
  initial_temperature: 100
  alpha: 0.95
  beta: 0.95
  stopping_temperature: 1e-6
  schedule: 'lundy_mees' # 'linear', 'geometric', 'lundy_mees'

Particle_Swarm_Optimization:
  num_particles: 10
  inertia: 0.65
  cognitive: 2.5
  social: 2.5

Genetic_Algorithm:
  population_size: 10
  selection_method: 'tournament' # 'tournament', 'roulette_wheel', 'rank_based'
  tournament_size: 3
  crossover_method: 'uniform' # 'uniform', 'one_point', 'two_point'
  crossover_rate: 0.8
  mutation_rate: 0.01 # should be small, better 1/self.stock_num
  replacement_method: 'elitism' # 'elitism', 'generational'


