tickers: ['AAPL', 'AMZN', 'GOOG', 'META', "NFLX"]
stock_data_path: "./data/"
max_total_iterations: 100
max_iterations: 100
risk_free_rate: 0.8877 # got this value by averaging the risk-free rates of the time period 2014.01.01 to 2019.12.31, refer to https://fred.stlouisfed.org/series/DTB3
min_weight: 0.01
metric: 'sharpe_ratio' # 'sharpe_ratio', 'sortino_ratio', 'max_drawdown', 'annualized_return', 'annualized_volatility'

Simulated_Annealing:
  initial_temperature: 100
  cooling_rate: 0.003
  stopping_temperature: 0.0001
  inertia: 0.7
  cognitive: 1.5
  social: 1.5
  schedule: 'linear' # 'linear', 'geometric', 'lundy_mees'

Particle_Swarm_Optimization:
  num_particles: 10

Genetic_Algorithm:
  population_size: 10
  selection_method: 'tournament' # 'tournament', 'roulette_wheel', 'rank_based'
  tournament_size: 3
  crossover_method: 'uniform' # 'uniform', 'one_point', 'two_point'
  crossover_rate: 0.8
  mutation_rate: 0.01 # should be small, better 1/self.stock_num
  replacement_method: 'elitism' # 'elitism', 'generational'

Ant_Colony_Optimization:
  num_ants: 10

Markowitz_Model:
